name = "IterTools"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
keywords = ["iterators", "itertools", "iteration"]
license = "MIT"
desc = "Common functional iterator patterns"
version = "1.10.0"

[compat]
julia = "1.8"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SparseArrays"]
